export default [
    { name: 'Aston Martin', CountryId: 1 },
    { name: 'FIAT', CountryId: 2 },
    { name: 'Alfa Romeo', CountryId: 3 },
    { name: 'BMW', CountryId: 4 },
    { name: 'Audi', CountryId: 5 },
    { name: 'ГАЗ', CountryId: 6 },
    { name: 'Volvo', CountryId: 7 },
    { name: 'Saab', CountryId: 8 },
    { name: 'Chrysler', CountryId: 9 },
    { name: 'Cord', CountryId: 10 },
    { name: 'ЗИЛ', CountryId: 11 },
    { name: 'Audi', CountryId: 12 },
    { name: 'Porsche', CountryId: 13 },
    { name: 'Volkswagen', CountryId: 14 },
    { name: 'Mercedes-Benz', CountryId: 15 },
    { name: 'Rolls-Royce', CountryId: 16 },
    { name: 'Jaguar', CountryId: 17 },
    { name: 'Bugatti', CountryId: 18 },
    { name: 'Delahaye', CountryId: 19 },
    { name: 'Cadillac', CountryId: 20 },
    { name: 'Stutz', CountryId: 21 },
    { name: 'Corvette', CountryId: 22 },
    { name: 'Lamborghini', CountryId: 23 },
    { name: 'Chevrolet', CountryId: 24 },
    { name: 'Imperial', CountryId: 25 },
    { name: 'Buick', CountryId: 26 },
    { name: 'Jaguar', CountryId: 27 },
    { name: 'Ferrari', CountryId: 28 },
]
